export const paquetes = [
    {   
        image: './../../image/cancun-tour.jpg',
        categoria: 'Paquetes Internacionales',
        lugar: 'Cancun',
        estacion: 'Verano',
        hotel: 'Hotel Riu Yucatan',
        cantEstrellas : 5,
        precio: '90.000',
    },
    {
        image: './../../image/rio-tour.jpg',
        categoria: 'Paquetes Internacionales',
        lugar: 'Brasil',
        estacion: 'Verano',
        hotel: 'Hotel Royal Rio Palace',
        cantEstrellas : 3,
        precio: '10.000',
    },
    {
        image: './../../image/turquia-tour.jpg',
        categoria: 'Paquetes Internacionales',
        lugar: 'Turquia',
        estacion: 'Invierno',
        hotel: 'Hotel Radisson Blu Istanbul Pera',
        cantEstrellas : 3,
        precio: '110.000',
    },
    {
        image: './../../image/paris-tour.jpg',
        categoria: 'Paquetes Internacionales',
        lugar: 'Francia',
        estacion: 'Otoño',
        hotel: 'Hotel Le Relais Saint Honoré',
        cantEstrellas : 3,
        precio: '25.000',
    },
    {
        image: './../../image/israel-tour.jpg',
        categoria: 'Paquetes Internacionales',
        lugar: 'Israel',
        estacion: 'Primavera',
        hotel: 'Hotel Dan Panorama Jerusalem',
        cantEstrellas : 5,
        precio: '125.000',
    },
    {
        image: './../../image/villa-huinid-hotel.jpg',
        categoria: 'Paquetes Nacionales',
        lugar: 'Bariloche',
        temporada: 'Alta',
        estacion: 'Invierno',
        hotel: 'Hotel Huinid Bustillo Hotel & Spa',
        cantEstrellas : 4,
        precio: '10.000',
    },
    {
        image: './../../image/villa-huapi-hotel.jpg',
        categoria: 'Paquetes Nacionales',
        lugar: 'Bariloche',
        temporada: 'Alta',
        estacion: 'Invierno',
        hotel: 'Villa Huapi',
        cantEstrellas : 4,
        precio: '8.000',
    },
    {
        image: './../../image/cristal-hotel.jpg',
        categoria: 'Paquetes Nacionales',
        lugar: 'Bariloche',
        temporada: 'Baja',
        estacion: 'Verano',
        hotel: 'Hotel Cristal',
        cantEstrellas : 2,
        precio: '12.000',
    },
    {
        image: './../../image/las-hayas-ushuaia-resort.jpg',
        categoria: 'Paquetes Nacionales',
        lugar: 'Usuhaia',
        temporada: 'Alta',
        estacion: 'Invierno',
        hotel: 'Hotel Las Hayas Ushuaia Resort',
        cantEstrellas : 5,
        precio: '15.000',
    },
    {
        image: './../../image/los-yamanas-hotel.jpg',
        categoria: 'Paquetes Nacionales',
        lugar: 'Usuhaia',
        temporada: 'Alta',
        estacion: 'Invierno',
        hotel: 'Los Yamanas Hotel & Health Club',
        cantEstrellas : 4,
        precio: '19.000',
    },
    {
        image: './../../image/nh-gran-hotel-provinciales.jpg',
        categoria: 'Paquetes Nacionales',
        lugar: 'Mar del Plata',
        temporada: 'Baja',
        estacion: 'Invierno',
        hotel: 'NH Gran Hotel Provinciales',
        cantEstrellas : 5,
        precio: '13.000',
    },
    {
        image: './../../image/rivera-sur-mar-del-plata.jpg',
        categoria: 'Paquetes Nacionales',
        lugar: 'Mar del Plata',
        temporada: 'Alta',
        estacion: 'Primavera',
        hotel: 'Ribera Sur Mar del Plata',
        cantEstrellas : 4,
        precio: '9.000',
    },
    {
        image: './../../image/hermitage-hotel.jpg',
        categoria: 'Paquetes Nacionales',
        lugar: 'Mar del Plata',
        temporada: 'Alta',
        estacion: 'Verano',
        hotel: 'Hermitage Hotel',
        cantEstrellas : 5,
        precio: '15.000',
    },
    {
        image: './../../image/gran-skorpios-hotel.jpg',
        categoria: 'Paquetes Nacionales',
        lugar: 'Mar del Plata',
        temporada: 'Baja',
        estacion: 'Otoño',
        hotel: 'Gran Hotel Skorpios',
        cantEstrellas : 3,
        precio: '7.000',
    },
    {
        image: './../../image/epic-hotel-sl.jpg',
        categoria: 'Paquetes Nacionales',
        lugar: 'San Luis',
        temporada: 'Alta',
        estacion: 'Otoño',
        hotel: 'Epic Hotel San Luis',
        cantEstrellas : 4,
        precio: '8.500',
    },
    {
        image: './../../image/hotel-regidor-sl.jpg',
        categoria: 'Paquetes Nacionales',
        lugar: 'San Luis',
        temporada: 'Baja',
        estacion: 'Invierno',
        hotel: 'Hotel Regidor',
        cantEstrellas : 3,
        precio: '6.000',
    },
    {
        image: './../../image/portal-plaza-suites-M.jpg',
        categoria: 'Paquetes Nacionales',
        lugar: 'Mendoza',
        temporada: 'Alta',
        estacion: 'Invierno',
        hotel: 'Portal Plaza Suites',
        cantEstrellas : 4,
        precio: '7.000',
    },
    {
        image: './../../image/sheraton-mendoza.jpg',
        categoria: 'Paquetes Nacionales',
        lugar: 'Mendoza',
        temporada: 'Alta',
        estacion: 'Invierno',
        hotel: 'Sheraton Mendoza Hotel',
        cantEstrellas : 5,
        precio: '16.000',
    },
    {
        image: './../../image/premier-hotel-T.jpg',
        categoria: 'Paquetes Nacionales',
        lugar: 'Tucuman',
        temporada: 'Alta',
        estacion: 'Primavera',
        hotel: 'Hotel Premier',
        cantEstrellas : 3,
        precio: '4.000',
    },
    {
        image: './../../image/crucero-msc.jpg',
        categoria: 'Crucero',
        crucero: 'MSC',
        lugar: 'Rio',
        camarotePrice: [
            {            
                exterior: '135.000',
                balcon: '140.000',
                suite: '150.000' 
            },
        ],
    },
    {
        image: './../../image/crucero-msc.jpg',
        categoria: 'Crucero',
        crucero: 'MSC',
        lugar: 'Europa',
        camarotePrice: [
            {            
                exterior: '175.000',
                balcon: '190.000',
                suite: '250.000' 
            },
        ],
    },
    {
        image: './../../image/crucero-royal.jpg',
        categoria: 'Crucero',
        crucero: 'Royal Caribbean',
        lugar: 'Caribe',
        camarotePrice: [
            {            
                exterior: '145.000',
                balcon: '160.000',
                suite: '190.000' 
            },
        ],
    },
    {
        image: './../../image/resort-nosy-be.jpg',
        categoria: 'Exoticos',
        lugar: 'Madagascar',
        estacion: 'Verano',
        hotel: 'Madagascar Resort Nosy Be',
        cantEstrellas : 3,
        precio: '125.000',
    },
    {
        image: './../../image/hotel-metropol-russia.jpg',
        categoria: 'Exoticos',
        lugar: 'Rusia',
        estacion: 'Invierno',
        hotel: 'Hotel Metropol Moscow',
        cantEstrellas : 5,
        precio: '86.000',
    },
    {
        image: './../../image/ibis-hotel.jpg',
        categoria: 'Exoticos',
        lugar: 'Tailandia',
        hotel: 'Ibis Bangkok Riverside',
        estacion: 'Primavera',
        cantEstrellas : 3,
        precio: '9.000',
    },
    {
        image: './../../image/burj-al-arab.jpg',
        categoria: 'Exoticos',
        lugar: 'Emiratos Arabes',
        estacion: 'Verano',
        hotel: 'Burj Al Arab',
        cantEstrellas : 5,
        precio: '360.000',
    },
]